version: '3.9'

services:
  app:
    build: 
      context: .
      target: dev
    env_file:
      - .env
    command: go run ./src/cmd/develop/main.go
    ports:
      - '9001:8080'
    restart: unless-stopped

  db:
    image: postgres:12.13-alpine3.17
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresgl/data
    restart: unless-stopped
    

volumes:
  postgres-db: {}

